app = "makeathon-2026-reply"
primary_region = "fra"

[build]

[env]
  TUM_ENV = "demo"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source = "session_data"
  destination = "/data"
